# -*- coding: utf-8 -*-
"""LLMs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kx1fqPlwP4kGRDJFvhOU0yYTRnX0r0fR
"""

!pip install openai

import os
import openai
import json

# load the API Key
with open('api json.json','r') as f:
  json_data=json.load(f)
  os.environ['OPENAI_API_KEY']=json_data['API_KEY2']
  openai.api_key=json_data['API_KEY2']
  os.environ['SERPAPI_API_KEY']=json_data['API_KEY']
response=openai.Completion.create(model="text-davinci-003",prompt="say this is a test",temperature=0,max_tokens=7)

print(response)

"""# Langchain for building chians"""

pip install langchain

# we will be using prompt template

from langchain.prompts import PromptTemplate
from langchain.llms import OpenAI
llm=OpenAI(temperature=0.9)
prompt=PromptTemplate(
    input_variables=["country"],
    template="What is the national sport of {country}"
)

from langchain.chains import LLMChain
chain=LLMChain(llm=llm,prompt=prompt)

# running the chain on specific input
print(chain.run('England'))

"""# agents: can dynamically call chains based on user input
--------------------------------------------------------------
A) Tool
B) LLM
C) Agent
"""

!pip install google-search-results

from langchain.agents import load_tools,initialize_agent,AgentType
from langchain.llms import OpenAI

# load the model
llm=OpenAI(temperature=0)

# next we will load some tools
tools=load_tools(["serpapi","llm-math"],llm=llm)

# initialize the agent
agent=initialize_agent(tools,llm,agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,verbose=True)

# run this agent
agent.run("What was the temperature in India")

